<a href="https://colab.research.google.com/github/pedroteche-ih/79_PT_JUN2022/blob/main/aulas/79_DA_PT_JUN_2022_Desafio_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Dada uma `array` numérica de tamanho NxM e uma posiçao inicial `(i, j)`, encontre todos os elementos da região contígua à `(i, j)` cujos valores tenham no máximo uma diferença de `k` para o valor de `(i, j)`.

Retorne o resultado como uma `array` de tamanho NxM com 1s indicando a região contínua e 0 nos pontos restantes.

Por exemplo, se o `array` original é:

In [13]:
np.array([[1,1,1,1,1],[1,2,1,3,3], [1,4,4,4,4], [5,5,5,5,5]])

array([[1, 1, 1, 1, 1],
       [1, 2, 1, 3, 3],
       [1, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

com `(i, j) = (0, 2)` e `k = 1` o resultado seria:

In [8]:
np.array([[1,1,1,1,1],[1,1,1,0,0], [1,0,0,0,0], [0,0,0,0,0]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

com `(i, j) = (2, 1)` e `k = 0` o resultado seria:

In [14]:
np.array([[0,0,0,0,0],[0,0,0,0,0], [0,1,1,1,1], [0,0,0,0,0]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

In [15]:
# SEU CÓDIGO AQUI